id: PB0547024
initial_creation_type: ocr
source_metadata:
  volumes:
    e4d74501a81a4a61891223f0d8abaddf:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: འཕགས་པ་སཱ་ལུ་ལྗང་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1498
      volume_number: 65
